export interface PlayerStatsRaw {
  id: number,
  name: string,
  team_id: number,
  team: string,
  games_played: number
  min: number,
  pts: number,
  reb: number,
  ast: number,
  stl: number,
  blk: number,
  tov: number,
  fgm: number,
  fga: number,
  ftm: number,
  fta: number,
  fg_pct: number,
  ft_pct: number,
  fg3m: number,
  last5_min: number,
  last5_pts: number,
  last5_reb: number,
  last5_ast: number,
  last5_stl: number,
  last5_blk: number,
  last5_tov: number,
  last5_fgm: number,
  last5_fga: number,
  last5_ftm: number,
  last5_fta: number,
  last5_fg_pct: number,
  last5_ft_pct: number,
  last5_fg3m: number
}

export interface PlayerStats extends PlayerStatsRaw {
  player_rating: number,
  last5_player_rating: number,
  fg_pct_rating: number,
  ft_pct_rating: number,
  last5_fg_pct_rating: number,
  last5_ft_pct_rating: number,
}